Changed hyphens in filenames to underscore. Fixed some 'fnd' issues.

diff --git a/bu-this b/bu-this
--- a/bu-this
+++ b/bu-this
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -16,29 +16,29 @@ Summary: Compress the contents of the Current Working Directory (CWD)
 
 '$(basename "$0")' performs the following actions:
 
-1. Obtain the path to the destination directory by invoking 'rabot_vars backupDir'
+1. Obtain the path to the destination directory by invoking 'rabot-vars backupDir'
    and create this directory if it doesn't already exist.
 
-2. Run the script 'tgz_this' to compress the contents of the CWD into a .tgz file
+2. Run the script 'tgz-this' to compress the contents of the CWD into a .tgz file
    located in the parent directory of the CWD.
 
 3. 'mv' this .tgz file to the destination directory.
 
-See also: 'tgz_this', 'zip_this', 'clean_this'
+See also: 'tgz-this', 'zip-this', 'clean-this'
 DOCSTRING
 
-require tgz_this
-require rabot_vars
+require tgz-this
+require rabot-vars
 
 # 1.
-destDir=$(rabot_vars backupDir)
+destDir=$(rabot-vars backupDir)
 
 mkdir -p "$destDir"
 exitOnError 1 "Error: the command 'mkdir -p \"$destDir\"' returned an error"
 
 # 2.
-tgzFile=$(tgz_this)
-exitOnError 1 "The script 'tgz_this' returned an error"
+tgzFile=$(tgz-this)
+exitOnError 1 "The script 'tgz-this' returned an error"
 
 if [ ! -f "$tgzFile" ]; then
     exitWith 1 "Error: the file '$tgzFile' doesn't exist"
diff --git a/logop/logop b/logop/logop
--- a/logop/logop
+++ b/logop/logop
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -31,13 +31,13 @@ adds a header and a footer section with supplementary information. If the
 second form is used however, this information will not contain the command
 string that has been invoked nor the exit status of the command.
 
-The logfile is saved in the folder obtained from invoking 'rabot_vars logDir'.
+The logfile is saved in the folder obtained from invoking 'rabot-vars logDir'.
 The filename of the logfile has the following form:
 
     YYYYMMDDhhmmss_RND.txt
 
 The part before the extension is the current time and a random alphanumerical
-string, as explained in 'timestamp_id --help'.
+string, as explained in 'timestamp-id --help'.
 
 In the log directory a symbolic link called 'latest' will be created or updated
 pointing to the newly created logfile.
@@ -75,17 +75,17 @@ A minimal sample of the second form:
 See also: 'logopd', 'logopf'
 DOCSTRING
 
-require timestamp_id
+require timestamp-id
 require fullts
-require logop_core
-require rabot_vars
+require logop-core
+require rabot-vars
 
-logDir="$(rabot_vars logDir)"
-fileName="$(timestamp_id).txt"
+logDir="$(rabot-vars logDir)"
+fileName="$(timestamp-id).txt"
 logFile="$logDir/$fileName"
 
 # Update symlink 'latest.txt' to point to latest logfile
 ln -sf "$fileName" "$logDir/latest.txt"
 
-. logop_core $*
+. logop-core $*
 
diff --git a/logop/logopd b/logop/logopd
--- a/logop/logopd
+++ b/logop/logopd
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -20,7 +20,7 @@ The behavior of '$(basename "$0")' is similar to 'logop', with the
 following differences:
 
 - An extra 'DIR' argument will override the value provided by
-  'rabot_vars logDir'.
+  'rabot-vars logDir'.
 
 - The symlink called 'latest.txt' in the default log directory will
   not be updated. Instead, a 'latest.txt' symlink is created/updated
diff --git a/tgz-files b/tgz-files
--- a/tgz-files
+++ b/tgz-files
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -44,15 +44,15 @@ With a file 'filelist.txt' containing the following two lines:
     two.txt
 
 The command and its output look like this:
-    user@host ~ $ tgz_files filelist.txt .
+    user@host ~ $ tgz-files filelist.txt .
     /home/user/one.txt
     /home/user/two.txt
     /home/user/20140519142819_5sp.tgz
 
-See also: 'tgz_folder', 'tgz_this'
+See also: 'tgz-folder', 'tgz-this'
 DOCSTRING
 
-require timestamp_id
+require timestamp-id
 
 fileList=$(readlink -f $1)
 if [ ! -f "$fileList" ]; then
@@ -69,8 +69,8 @@ if [ -n "$3" ]; then
     prefix=$3_
 fi
 
-tsid=$(timestamp_id)
-exitOnError 1 "Error while running \"timestamp_id\""
+tsid=$(timestamp-id)
+exitOnError 1 "Error while running \"timestamp-id\""
 
 destFile="$destDir/$prefix$tsid.tgz"
 #cd
diff --git a/zip-folder b/zip-folder
--- a/zip-folder
+++ b/zip-folder
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -29,13 +29,13 @@ Paths inside the .zip file will be relative to the current working directory.
 
 Example:
 
-    user@host ~ $ zip_folder somedir/myfolder .
+    user@host ~ $ zip-folder somedir/myfolder .
     /home/user/myfolder_20140522224809_m94.zip
 
-See also: 'zip_this', 'tgz_folder', 'tgz_this'
+See also: 'zip-this', 'tgz-folder', 'tgz-this'
 DOCSTRING
 
-require timestamp_id
+require timestamp-id
 require zip
 
 if [ ! -d "$1" ]; then
@@ -50,8 +50,8 @@ if [ ! -w "$2" ]; then
     exitWith 1 "Error: the destination folder '$2' isn't writable"
 fi
 
-tsid=$(timestamp_id)
-exitOnError 1 "The script 'timestamp_id' returned an error."
+tsid=$(timestamp-id)
+exitOnError 1 "The script 'timestamp-id' returned an error."
 
 prefix=${3:-$(basename $(readlink -f $1))}
 exitOnError 1 "Could not set the prefix."
