Changed underscores in filenames to hyphens. Fixed some 'fnd' issues.

diff --git a/fnd b/fnd
--- a/fnd
+++ b/fnd
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -25,7 +25,7 @@ names=".git .svn .hg .bzr CVS"
 expression=
 
 while read name; do
-   expression="$expression ""! -path */$name ! -path */$name/*"
+   expression="$expression ! -path */$name ! -path */$name/*"
 done < <(tr ' ' $'\n' <<< "$names")
 
 find $* $expression
diff --git a/fullts b/fullts
--- a/fullts
+++ b/fullts
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -15,7 +15,7 @@ Usage: $(basename "$0") [FILE]
 'YYYMMDDhhmmss'. If the argument FILE is given, it displays
 the timestamp of FILE in this format.
 
-See also: 'timestamp_id'
+See also: 'timestamp-id'
 DOCSTRING
 
 if [ -z "$1" ]; then
diff --git a/tgz-this b/tgz-this
--- a/tgz-this
+++ b/tgz-this
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -17,29 +17,29 @@ to a .tgz file stored in its parent directory.
 '$(basename "$0")' performs the following actions:
 
 1. Remove temporary files from the CWD by running the script
-   'clean_this'.
+   'clean-this'.
 
 2. 'cd' into the parent directory of the CWD and run
-   the script 'tgz_folder' on the former CWD.
+   the script 'tgz-folder' on the former CWD.
 
 Example:
 
-    user@host ~/myfolder $ tgz_this
+    user@host ~/myfolder $ tgz-this
     /home/user/myfolder_20140522221601_5ve.tgz
 
-See also: 'tgz_folder', 'tgz_files'
+See also: 'tgz-folder', 'tgz-files'
 DOCSTRING
 
-require clean_this
-require tgz_folder
+require clean-this
+require tgz-folder
 
 folderPath=$(pwd)
 folderName=$(basename $folderPath)
 fullScriptPath=$(readlink -f "$0")
 
 # 1.
-clean_this
-exitOnError 1 "The script 'clean_this' returned an error."
+clean-this
+exitOnError 1 "The script 'clean-this' returned an error."
 
 cd ..
 exitOnError 1 "Could not perform 'cd ..'"
@@ -49,6 +49,6 @@ if [ "$(pwd)" = "$folderPath" ]; then
   exit -1
 fi
 
-tgz_folder "$folderName" .
-exitOnError 1 "The script 'tgz_folder' returned an error"
+tgz-folder "$folderName" .
+exitOnError 1 "The script 'tgz-folder' returned an error"
 
diff --git a/timestamp-id b/timestamp-id
--- a/timestamp-id
+++ b/timestamp-id
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -21,7 +21,7 @@ and 'RND' is the random string (produced by 'randid').
 
 Example:
 
-    user@host ~ $ timestamp_id
+    user@host ~ $ timestamp-id
     20140328133629_1oy
 
 See also: 'fullts', 'randid'
diff --git a/zip-this b/zip-this
--- a/zip-this
+++ b/zip-this
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot_common
+. rabot-common
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot_common" >&2
+  echo "$0: Error while sourcing rabot-common" >&2
   exit 1
 fi
 
@@ -17,29 +17,29 @@ to a .zip file stored in its parent directory.
 '$(basename $0)' performs the following actions:
 
 1. Remove temporary files from the CWD by running the script
-   'clean_this'.
+   'clean-this'.
 
 2. 'cd' into the parent directory of the CWD and run
-   the script 'zip_folder' on the former CWD.
+   the script 'zip-folder' on the former CWD.
 
 Example:
 
-    user@host ~/myfolder $ zip_this
+    user@host ~/myfolder $ zip-this
     /home/user/myfolder_20140522225226_0fg.zip
 
-See also: 'zip_folder', 'tgz_this'
+See also: 'zip-folder', 'tgz-this'
 DOCSTRING
 
-require clean_this
-require zip_folder
+require clean-this
+require zip-folder
 
 folderPath=$(pwd)
 folderName=$(basename $folderPath)
 fullScriptPath=$(readlink -f $0)
 
 # 1.
-clean_this
-exitOnError 1 "The script 'clean_this' returned an error."
+clean-this
+exitOnError 1 "The script 'clean-this' returned an error."
 
 # 2.
 cd ..
@@ -50,7 +50,7 @@ if [ "$(pwd)" = "$folderPath" ]; then
   exit -1
 fi
 
-zip_folder "$folderName" .
-exitOnError 1 "The script 'tgz_folder' returned an error"
+zip-folder "$folderName" .
+exitOnError 1 "The script 'tgz-folder' returned an error"
 
 
